### ISSUE TITLE
Comments on the paper

### ISSUE THREAD

**Issue by HenriKajasilta** [realxinzhao/gcamfaostat#11]
The functionality and intended use of the package are clearly stated. However, the length of the paper is well over 1000 words as instructed. The chapter on _Design and Functionality_ could probably be summarised with a high-level illustration of _preparation_, _processing_ and _visualisation_. The detailed overview of these stages can be found on the gh-pages anyway.

- [x] Check and fix the length of the paper.

It wasn't really mentioned if there are similar applications/packages available. Based on the paper, at least not as comprehensive as `gcamfaostat`, but it would have been interesting to have some references, if something similar is available. However, the paper states: "_It is noteworthy that each “agroeconomic modeling team typically develops its own assumptions and methods to prepare and process FAOSTAT data_", which I interpret to mean that most of the data processing is not done by off-the-shelf systems.

- [x] Suggestion: Indicate if there are other packages which are similar to `gcamfaostat`.

**Comment by realxinzhao** [comment]
> Check and fix the length of the paper.

@HenriKajasilta thank you so much for pointing this out and for the suggestions. We have now made a significant cut of the manuscript. Visualization and other functions were cut. The Design and Functionality section overall is reduced. However, it is still around 1500 (not including captions/reference). Please let us know if this is fine (given that it's the first of its kind package so we wanted to include more communication to the audience). We are also happy to make more cuts if needed.

> Indicate if there are other packages which are similar to gcamfaostat.

Thanks! We added this sentence to the Statement of Need: "To the best of our knowledge, such a tool has not been developed yet."

**Comment by HenriKajasilta** [comment]
I would still consider shortening the paper as it is considerably longer than the 1000 word limit. In addition, _Key functions_ sections contain detailed commands on how to run the application, whereas the paper only expects a high-level description, and I would see fit to reduce the description of details here.

**Comment by realxinzhao** [comment]
> I would still consider shortening the paper as it is considerably longer than the 1000 word limit. In addition, _Key functions_ sections contain detailed commands on how to run the application, whereas the paper only expects a high-level description, and I would see fit to reduce the description of details here.

Sounds good. I will further reduce the `key functions` section. Thanks!

**Comment by realxinzhao** [comment]
@HenriKajasilta 
We further simplified the writing and restructured the Design and Functionality section to reduce the length to <1200 if only accounting for the main components. The structure is much more balanced now.  Please take a look when you have a chance. Thanks!
